### ISSUE TITLE
Question about Visitor Iterator

### ISSUE THREAD

**Issue by guiled** [hoaproject/Visitor#24]
I have a problem with compiler : when I visit an AST with the basic Interpreter there are some "internal problems" due to the nature of PP Language ( LL(k) )
I decided to transform the LL(k) AST into a LR AST with an other Visitor called LL2LR (with some simple TreeNode switches)

So I have a code like this
```php
$ast = $compiler->parse($input);
$ll2lr->visit($ast);
$interpreter->visit($ast);
```

Everything works well today. I will make an other Visitor that receives the two existing visitors (`$compiler` and `$ll2lr`) and will Visit the ast by visiting it with each visitor.

The question : do you think it could be interesting to have it officially somewhere in Hoaproject/Visitor or Hoaproject/Iterator ?

**Comment by Hywan** [comment]
Hi,

I can't judge until I can see the code. If it should land somewhere, it is in this library :-).
